export const SET_NAVIGATION = "SET_NAVIGATION"

export const SET_LANGUAGE = "SET_LANGUAGE"

export const INIT_TAGS = "INIT_TAGS"
export const SET_TAGS = "SET_TAGS"
export const DELETE_TAGS = "DELETE_TAGS"
export const INIT_ARTICLES = 'INIT_ARTICLES'
export const ADD_TAG= "ADD_TAG"
export const DELETE_ARTICLES = "DELETE_ARTICLES"
export const ARTICLE_PUBLICATION = "ARTICLE_PUBLICATION"